[package]
name = "supapasskeys_webauthn"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "supapasskeys_webauthn"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = {version = "0.30.0", features = ["nif_version_2_17"]}
