# © Copyright 2024 Cozy Bytes GmbH

header:
  - license:
      spdx-id: Apache-2.0
      copyright-owner: Cozy Auth Contributors
      copyright-year: "2024"
    paths-ignore:
      - ".dockerignore"
      - ".editorconfig"
      - ".env-example"
      - "Dockerfile"
      - "Cargo.lock"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - ".sqlx/**"
      - "ee/**"
      - "rel/**"
      - "priv/static/**"
      - "priv/gettext/**"
      - "assets/vendor/**"
      - "**/target/**"
      - "**/*.toml"
      - "**/*.lock"
      - "**/*.yml"
    language:
      Elixir:
        extensions:
          - ".ex"
          - ".exs"
        comment_style_id: Hashtag
      HTML:
        extensions:
          - ".heex"
        comment_style_id: AngleBracket
  - license:
      content: © Copyright 2024 Cozy Bytes GmbH
    paths:
      - "ee/**"
    paths-ignore:
      - "LICENSE"
      - "**/*.toml"
