[package]
name = "supapasskeys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0", features = ["json", "uuid"] }
rocket_db_pools = { version = "0.1.0", features = ["sqlx_postgres"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_cbor = "0.11.2"
sqlx = { version = "0.7.2", features = ["runtime-tokio-rustls", "any", "postgres", "migrate", "uuid"] }
uuid = { version = "1.6.1", features = ["v4"] }
webauthn-rs = { version = "0.4.8", features = ["danger-allow-state-serialisation"] }
webauthn-rs-proto = "0.4.9"
