[package]
name = "supapasskeys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["http2", "ws"] }
futures = "0.3.29"
futures-sink = "0.3.29"
tokio = { version = "1.34.0", features = ["full"] }
uuid = { version = "1.5.0", features = ["v4"] }
webauthn-rs = "0.4.8"
