[workspace]
members = [ "cli","ee/cloud", "server"]
resolver = "2"

[workspace.dependencies]
axum = "0.7.5"
clap = "4.5.16"
serde_json = "1.0.124"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = "1.39.1"
