
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: supapasskeys_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432
