# fly.toml app configuration file generated for cozyauth-little-hill-4941 on 2024-08-20T18:51:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cozyauth'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build.args]
BINARY = "cozyauth-cloud"

[deploy]
release_command = 'migrate'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
