[package]
name = "supapasskeys_petname"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "supapasskeys_petname"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
blake2 = "0.10.6"
hex = "0.4.3"
petname = "1.1.3"
rand = "0.8.5"
rustler = "0.31.0"
