[package]
name = "supapasskeys_petname"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "supapasskeys_petname"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
petname = "1.1.3"
rustler = "0.30.0"
