name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    - name: Compiles and builds
      run: cargo build --verbose
      working-directory: ./api
    - name: Check Formatting
      run: cargo fmt -- --check
      working-directory: ./api
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./api

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ github.ref == 'refs/heads/main' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.actor }}/supapasskeys-api:latest
