name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    - name: Compiles and builds
      run: cargo build --verbose
    - name: Check Formatting
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
