name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-app:
    name: Build and test application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.39.1
    - name: Install dependencies
      run: npm ci
    - name: Compiles and builds
      run: npm run build
    - name: Run linter
      run: npm run lint

  test-api:
    name: Build and test API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    - name: Compiles and builds
      run: cargo build --verbose
      working-directory: ./api
    - name: Check Formatting
      run: cargo fmt -- --check
      working-directory: ./api
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./api

  build-api:
    name: Build container image for API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: false
          tags: ghcr.io/${{ github.actor }}/supapasskeys-api:latest
